{{- if and .Values.rbac.create .Values.rbac.createClusterAggregationRoles -}}
---
# Aggregate to built-in "edit" ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulumi-operator.fullname" . }}-edit
  labels:
    {{- include "pulumi-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: [pulumi.com]
    resources: [stacks, programs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [auto.pulumi.com]
    resources: [workspaces, updates]
    verbs: [get, list, watch, create, update, patch, delete]
---
# Aggregate to built-in "view" ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulumi-operator.fullname" . }}-view
  labels:
    {{- include "pulumi-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: [pulumi.com]
    resources: [stacks, programs]
    verbs: [get, list, watch]
  - apiGroups: [auto.pulumi.com]
    resources: [workspaces, updates]
    verbs: [get, list, watch]
{{- end }}
